language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - main
install:
  - yarn install
jobs:
  include:
    - stage: lint
      script:
        - yarn prettier --check --config .prettierrc ./src
stages:
  - lint
